'@startuml
skinparam defaultFontName "Noto Sans CJK SC"
skinparam defaultFontSize 14
title 基础信息管理用例
skinparam linetype ortho

actor "管理员" as A
actor "最高管理者" as SA

(管理充电站)
(管理充电桩)
(管理用户)

A --> 管理充电站
A --> 管理充电桩
A --> 管理用户
SA --> 管理充电站
SA --> 管理充电桩
SA --> 管理用户

管理充电站 <.down. 管理充电桩 : <<extend>>
@enduml