'@startuml
skinparam defaultFontName "Noto Sans CJK SC"
skinparam defaultFontSize 14
title 管理端用例
skinparam useCaseShape rectangle

actor "管理员" as A
actor "最高管理者" as SA
actor "维修人员" as M

usecase "管理充电站" as MS
usecase "管理充电桩" as MC
usecase "管理用户" as MU
usecase "用户权限管理" as PM
usecase "处理报修" as HR
usecase "查看报修记录" as VR
usecase "强制结束充电" as FSC
usecase "生成统计报表" as GS
usecase "充电桩状态快捷查询" as QC

A --> MS
A --> MC
A --> MU
A --> PM
A --> HR
A --> VR
A --> FSC
A --> QC
SA --> MS
SA --> MC
SA --> PM
SA --> GS
SA --> FSC
SA --> QC
M --> HR
M --> VR
@enduml